// This file was generated by silverstripe/cow from client/lang/src/en.json.
// See https://github.com/silverstripe/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "CKANResourceLocatorField.CHANGES_WARNING": "Please note: Changing the data source URL or resource will clear all existing columns and filters when saving the page.",
    "CKANResourceLocatorField.DATA_SOURCE_URL": "Data source URL",
    "CKANResourceLocatorField.INVALID_DATASET_URL": "The provided data source URL does not appear to be a valid CKAN data set.",
    "CKANResourceLocatorField.INVALID_RESOURCE_SELECTION": "Datastore is not available for the selected resource.",
    "CKANResourceLocatorField.RESOURCE_NAME": "Resource name",
    "CKANRegistryDetailView.BACK": "Back",
    "CKANRegistryDetailView.LOADING": "Loading...",
    "CKANRegistryDetailView.NO_RESULTS": "No results found!",
    "CKANRegistryDisplay.DOWNLOAD": "Export results to CSV"
});
}