// This file was generated by silverstripe/cow from client/lang/src/eo.json.
// See https://github.com/silverstripe/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('eo', {
    "CKANResourceLocatorField.CHANGES_WARNING": "Bonvolu noti: ŝanĝi la datumfontan URL aŭ rimedon, vakigos ĉiujn ekzistantajn kolumnojn kaj filtrilojn kiam vi konservas la paĝon.",
    "CKANResourceLocatorField.DATA_SOURCE_URL": "Datumfonta URL",
    "CKANResourceLocatorField.INVALID_DATASET_URL": "La donita datumfonta URL ŝajnas ne esti valida CKAN-datumfonto.",
    "CKANResourceLocatorField.INVALID_RESOURCE_SELECTION": "Datuma konservejo ne disponeblas por la elektita rimedo.",
    "CKANResourceLocatorField.RESOURCE_NAME": "Nomo de rimedo",
    "CKANRegistryDetailView.BACK": "Retro",
    "CKANRegistryDetailView.LOADING": "Ŝargas...",
    "CKANRegistryDetailView.NO_RESULTS": "Ne trovis rezultojn!",
    "CKANRegistryDisplay.DOWNLOAD": "Eksporti rezultojn al CSV"
});
}